### ISSUE TITLE
bump_commit should follow semver

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-blacksmith#21]
this could be a configuration option that makes blacksmith inspect the commit log since the last tag to determine whether to do a patch, minor or major bump.

[AngularJS has very useful commit conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#) which are used by [semantic-release](https://github.com/boennemann/semantic-release) to do exactly that.

**Comment by carlossg** [comment]
looks good, but I don't know how many people will use the commit message conventions if not enforced...

**Comment by igalic** [comment]
approximately 0…

there is, of course, tooling around that: [validate commit messages](https://github.com/kentcdodds/validate-commit-msg) and the [commitizen cli](https://github.com/commitizen/cz-cli)

**Comment by jyaworski** [comment]
What's the status of this?

**Comment by igalic** [comment]
@jyaworski the status of this is still wishful thinking :D

**Comment by ekohl** [comment]
In Voxpupuli changelogs are created using github-changelog-generator which uses labels. IMHO we should use that but I don't think it should be done in this gem. Should we close this as WONTFIX?

**Comment by ekohl** [comment]
Given there's no response, I'm going to close this and leave it up to a higher layer to work on this.
