### ISSUE TITLE
Integration with changelog generator

### ISSUE THREAD

**Issue by solarkennedy** [voxpupuli/puppet-blacksmith#25]
I've recently started doing automatic changelog generation with:
https://github.com/skywinder/github-changelog-generator

But I would like to not have to "remember" to run it all the time.

Can you recommend how one would might integrate automatic changelog generation when someone does `module:release`? Hopefully it wouldn't require changes to the blacksmith code, maybe some rake magic?

**Comment by igalic** [comment]
that pulls in a lot of dependencies, and the results are rather unconvincing…

with our modules we try to keep a process similar to that of puppetlabs (and they're considering to copy ours?!?), see https://github.com/puppet-community/puppet-community.github.io/pull/22

**Comment by solarkennedy** [comment]
@igalic that looks great. Can you hint me at a rake task file that has the `travis_release` target? I can't find it in that repo. I found this gist? https://gist.github.com/igalic/ead06d1997506def97dc Do you have something more canonical?

**Comment by igalic** [comment]
@solarkennedy yeah, we have this in [puppet-extlib's Rakefile](https://github.com/voxpupuli/puppet-extlib/blob/master/Rakefile#L39-L69):
```ruby
desc 'release new version through Travis-ci'
task "travis_release" do

  require 'puppet_blacksmith/rake_tasks'
  Blacksmith::RakeTask.new do |t|
    t.build = false # do not build the module nor push it to the Forge
    # just do the tagging [:clean, :tag, :bump_commit]
  end

  m = Blacksmith::Modulefile.new
  v = m.version
  raise "Refusing to release an RC or build-release (#{v}).\n" +
        "Please set a semver *release* version." unless v =~ /^\d+\.\d+.\d+$/

  Rake::Task[:check_changelog].invoke
  # do a "manual" module:release (clean, tag, bump, commit, push tags)
  Rake::Task["module:clean"].invoke

  # idempotently create tags
  g = Blacksmith::Git.new
  Rake::Task["module:tag"].invoke unless g.exec_git("tag -l v#{v}").strip == "v#{v}"

  v_inc = m.increase_version(v)
  v_new = "#{v_inc}-rc0"
  ENV['BLACKSMITH_FULL_VERSION'] = v_new
  Rake::Task["module:bump:full"].invoke

  # push it out, and let travis do the release:
  g.commit_modulefile!(v_new)
  g.push!
end
```
but we'll probably move it to modulesync_config soon (see https://github.com/voxpupuli/modulesync_config/issues/45)

**Comment by solarkennedy** [comment]
Perfect! This is all I really wanted, a way to wrap blacksmith and changelog (and other junk) together. Thanks!
