### ISSUE TITLE
Setup Rubygems publishing

### ISSUE THREAD

**Issue by nibalizer** [voxpupuli/puppet-blacksmith#27]
This can be done through travis or by @carlossg sharing credentials with puppet-community admins.

**Comment by logicminds** [comment]
This is one of my favorite gems for creating gems: https://github.com/technicalpickles/jeweler and does the same thing as puppet-blacksmith but for gems. 

Its has some awesome rake tasks. And one of them is for releasing gems to ruby gems.org.  You could probably just take some of those tasks for this gem or add jeweler as a development dependency.

**Comment by carlossg** [comment]
voxpupuli is already an owner of the gem, what else needs to be done?
https://rubygems.org/gems/puppet-blacksmith

**Comment by nibalizer** [comment]
Integration work needs to be done

**Comment by rnelson0** [comment]
@carlossg thanks for uploading a new version to rubygems!
