### ISSUE TITLE
post rake module release, metadata.json version and git tag are not in sync

### ISSUE THREAD

**Issue by CUXIDUMDUM** [voxpupuli/puppet-blacksmith#28]
When we use rake:release 

https://github.com/voxpupuli/puppet-blacksmith/blob/master/lib/puppet_blacksmith/rake_tasks.rb#L87
release_dependencies = @build ? [:clean, :build, :tag, :push, :bump_commit] : [:clean, :tag, :bump_commit]

It is doing tag first and them bumping metadata.json via bump_commit.
Ideally we should update the metadata.json file and add it , commit it and then tag it and push it to remote.

release_dependencies = @build ? [:clean, :build,  :bump_commit, :tag, :push,] : [:clean, :bump_commit, :tag]

so that
$ git tag | tail -1
v0.1.5

$ grep '"version":' metadata.json
  "version": "0.1.5",

are same on github when module is released?
Correct?

**Comment by carlossg** [comment]
version in git is always ahead of last tag. After tagging development starts in the *next* version
This is so you inadvertently don't use a development version instead of a release version.
