### ISSUE TITLE
v4.0 release has broken my CI :( 

### ISSUE THREAD

**Issue by fatmcgav** [voxpupuli/puppet-blacksmith#52]
Morning all... 

I just wanted to flag an issue whereby the v4.0 release of Puppet-Blacksmith has broken our CI pipeline :( 

We're currently running tests using Ruby 1.9.3 against Puppet 3.8 (Yes, I know it's deprecated, we're working on it...)
The new v4.0 release bumps the dep on 'rest-client', which has a hard dep on Ruby >=2.0. 

Would it be possible to get the Puppet-Blacksmith gem updated with min Ruby versions? Atleast then, anyone using Ruby <2.0 should automatically pull in Puppet-Blacksmith 3.x... 

Edit: Yes, I can work-around the issue by pinning in Gemfile. However it took me best part of the morning to identify which Gem had changed and was causing my issue :(

**Comment by ekohl** [comment]
I'm somewhat new to publishing gems but I think we should publish a 4.0.1 and then pull 4.0.0 from rubygems. Is that correct?

**Comment by fatmcgav** [comment]
@ekohl I think that's probably the safest approach...

**Comment by ekohl** [comment]
I can prepare a 4.0.1 but will need someone with more permissions to pull the 4.0.0 then.

**Comment by rnelson0** [comment]
I don't have the access, but if it's helpful here's the process: http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem
@bastelfreak
