### ISSUE TITLE
Add support for Pulp Puppet Repositories

### ISSUE THREAD

**Issue by dhollinger** [voxpupuli/puppet-blacksmith#56]
Add support to publish to Pulp-based Puppet Repositories using the Pulp API. This should only apply to `push` and/or `release` tasks as Pulp is compliant with Forge formatted packages.

**Comment by ekohl** [comment]
Pulp 2 is being deprecated and for Pulp 3 there is no Puppet module storage planned so I'm going to close this. A PR would still be welcome, but I doubt anyone is going to work on it.
