### ISSUE TITLE
Support uploading to Katello repositories

### ISSUE THREAD

**Issue by dhollinger** [voxpupuli/puppet-blacksmith#67]
While adding support for uploading to `pulp` repositories is in here already (Katello uses Pulp on the backend), I think it's a good idea to add a separate issue for Katello as it has its own RESTful API the communicates to Pulp. Pulp's API should not be directly used when using Katello as the front-end.

**Comment by ekohl** [comment]
Pulp 2 is being deprecated and for Pulp 3 there is no Puppet module storage planned so I'm going to close this. A PR would still be welcome, but I doubt anyone is going to work on it.
